Repository mavenlink/design-system, pull requests merged in 2020-11, with the labels that each got.

#238 Webinf multi choice keyboard input 174782329
  CHANGELOG.md
  src/components/tag-list/tag-list.jsx
Labels: bug, component

#240 Release 0 51 2
  CHANGELOG.md
  package.json
Labels: bug, release

#234 Open sans: 400, 600
  .github/pull_request_template.md
  CHANGELOG.md
  package.json
  postcss.config.js
  styleguide.config.js
  styleguide.config.styles.js
  styleguide/content/brand-identity/typography.md
  styleguide/webpack.config.js
  yarn.lock
Labels: bug

#241 v0.51.3
  CHANGELOG.md
  package.json
Labels: release

#242 Release 0.52.0
  CHANGELOG.md
  package.json
Labels: release

#243 Deprecate `react-test-renderer` in test patterns
  src/components/button/__snapshots__/button.test.jsx.snap
  src/components/button/button.test.jsx
  src/components/form-control/__snapshots__/form-control.test.jsx.snap
  src/components/form-control/form-control.test.jsx
  src/components/list-option/__snapshots__/list-option.test.jsx.snap
  src/components/list-option/list-option.test.jsx
  src/components/page-header/__snapshots__/page-header.test.jsx.snap
  src/components/page-header/page-header.test.jsx
  src/components/section-row/__snapshots__/section-row.test.jsx.snap
  src/components/section-row/section-row.test.jsx
  src/components/section/__snapshots__/section.test.jsx.snap
  src/components/section/section.test.jsx
  src/components/table/__snapshots__/table.test.jsx.snap
  src/components/table/table.test.jsx
  src/components/tag-skill/__snapshots__/tag-skill.test.jsx.snap
  src/components/tag-skill/tag-skill.test.jsx
  yarn.lock
Labels: misc, refactor

#244 Get the debounced submit to just be a regular submit
  CHANGELOG.md
  src/components/form/form.jsx
  src/components/form/form.test.jsx
Labels: bug

#246 Cut a release
  CHANGELOG.md
  package.json
Labels: release

#245 Fix bug with datepicker in Safari
  CHANGELOG.md
  src/components/custom-field-input-date/custom-field-input-date.jsx
Labels: bug

#247 Release 0.52.2
  CHANGELOG.md
  package.json
Labels: release
