Repository mavenlink/design-system, pull requests merged in 2020-07, with the labels that each got.

#139 Webinf typography stuff
  CHANGELOG.md
  styleguide/content/brand-identity/typography.md
Labels: misc

#140 [webinf-we-gonna-be-alright-173455369] Selection works in CustomFieldInputSingleChoice
  CHANGELOG.md
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.md
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/components/list-option/list-option.jsx
  src/components/list-option/list-option.md
  src/components/list-option/list-option.test.jsx
  src/components/listbox/__snapshots__/listbox.test.jsx.snap
  src/components/listbox/listbox.jsx
  src/components/listbox/listbox.md
  src/components/listbox/listbox.test.jsx
Labels: component

#141 [webinf-why-s-single-choice-crying-173455213] MDS interactive single choice custom field component (3/5)
  CHANGELOG.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
Labels: component

#142 Interactive custom field multi choice has a popup
  CHANGELOG.md
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/form-control/__snapshots__/form-control.test.jsx.snap
  src/components/form-control/form-control.jsx
  src/components/form-control/form-control.test.jsx
  src/components/input/__snapshots__/input.test.jsx.snap
  src/components/list-option/__snapshots__/list-option.test.jsx.snap
  src/components/list-option/list-option.jsx
  src/components/list-option/list-option.test.jsx
  src/components/listbox/listbox.jsx
  src/components/listbox/listbox.test.jsx
  src/components/tag-list/tag-list.jsx
  src/components/tag-list/tag-list.test.jsx
  src/components/tag/tag.jsx
  src/components/tag/tag.md
  src/components/tag/tag.test.jsx
Labels: component

#144 Interactive multi choice autocompleter
  CHANGELOG.md
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-text/custom-field-input-text.css
Labels: component

#146 Implement `helpText` prop API on CustomFieldMultipleChoice component
  CHANGELOG.md
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/icon/__snapshots__/icon.test.jsx.snap
  src/components/icon/icon.jsx
  src/components/icon/icon.test.jsx
  src/components/tag-list/__snapshots__/tag-list.test.jsx.snap
  src/components/tag-skill/__snapshots__/tag-skill.test.jsx.snap
  src/components/tag/__snapshots__/tag.test.jsx.snap
  src/components/tag/tag.jsx
  src/svgs/icon-clear-small.svg
Labels: component

#149 Upgrade React Styleguidist
  README.md
  docs/decisions.md
  package.json
  src/components/button/button.md
  src/components/custom-field-input-currency/custom-field-input-currency.md
  src/components/custom-field-input-date/custom-field-input-date.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-number/custom-field-input-number.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.md
  src/components/custom-field-input-text/custom-field-input-text.md
  src/components/form-control/form-control.md
  src/components/icon-all/icon-all.css
  src/components/icon-all/icon-all.jsx
  src/components/icon-all/icon-all.md
  src/components/icon-all/index.js
  src/components/icon/icon.md
  src/components/input/input.md
  src/components/list-option/list-option.md
  src/components/listbox/listbox.md
  src/components/page-header/page-header.md
  src/components/section-row/section-row.md
  src/components/section/section.md
  src/components/table/table.md
  src/components/tag-list/tag-list.md
  src/components/tag-skill/tag-skill.md
  src/components/tag/tag.md
  styleguide.config.js
  styleguide/components/hero/animations.jsx
  styleguide/components/hero/hero.css
  styleguide/components/hero/hero.jsx
  styleguide/components/section/section.jsx
  styleguide/content/icons/index.js
  styleguide/content/icons/index.md
  styleguide/content/utils/page-view.js
  yarn.lock
Labels: site

#152 v0.29.0
  CHANGELOG.md
  package.json
Labels: release

#153 v0.30.0
  CHANGELOG.md
  package.json
Labels: release

#145 [webinf-two-hundred-years-of-custom-fields-171681529]
  CHANGELOG.md
  src/components/__internal__/abstract-custom-field.css
  src/components/__internal__/abstract-custom-field.jsx
  src/components/__internal__/abstract-custom-field.test.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.md
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-number/custom-field-input-number.test.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.css
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.md
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/hooks/use-validation.jsx
  src/hooks/use-validation.test.jsx
  yarn.lock
Labels: bug

#155 v0.31.0
  CHANGELOG.md
  package.json
Labels: release

#148 Webinf currency is what you think it is 171681533
  CHANGELOG.md
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.md
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-date/custom-field-input-date.test.jsx
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-number/custom-field-input-number.test.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.md
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
Labels: component, misc

#158 v0.32.0
  CHANGELOG.md
  package.json
Labels: release

#157 [webinf-i-thought-i-was-only-acting-173779664]
  CHANGELOG.md
  src/components/__internal__/abstract-custom-field/abstract-custom-field.css
  src/components/__internal__/abstract-custom-field/abstract-custom-field.jsx
  src/components/__internal__/abstract-custom-field/abstract-custom-field.test.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.css
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/no-options/no-options.css
  src/components/no-options/no-options.jsx
  src/components/no-options/no-options.md
Labels: component, refactor

#159 Release 0.33.0
  CHANGELOG.md
  package.json
Labels: release

#162 Colors upgrade guide
  styleguide/content/brand-identity/colors.md
Labels: site

#163 v0.34.0
  CHANGELOG.md
  package.json
Labels: release

#156 Improves accessibility of single and multi choice
  CHANGELOG.md
  src/components/__internal__/abstract-custom-field/abstract-custom-field.jsx
  src/components/__internal__/abstract-custom-field/abstract-custom-field.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/form-control/form-control.jsx
  src/components/form-control/form-control.test.jsx
  src/components/icon/__snapshots__/icon.test.jsx.snap
  src/components/icon/icon.jsx
  src/components/icon/icon.test.jsx
  src/components/tag-list/__snapshots__/tag-list.test.jsx.snap
  src/components/tag-skill/__snapshots__/tag-skill.test.jsx.snap
  src/components/tag/__snapshots__/tag.test.jsx.snap
  src/components/tag/tag.jsx
Labels: accessibility

#161 Bump testing library; Use toHaveDescription
  jest.config.js
  package.json
  src/components/__internal__/abstract-custom-field/abstract-custom-field.test.jsx
  yarn.lock
Labels: misc
