Repository mavenlink/design-system, pull requests merged in 2020-06, with the labels that each got.

#116 Tag component
  CHANGELOG.md
  package.json
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/icon/example.css
  src/components/icon/icon.css
  src/components/icon/icon.jsx
  src/components/icon/icon.md
  src/components/icon/icon.test.jsx
  src/components/tag-skill/__snapshots__/tag-skill.test.jsx.snap
  src/components/tag-skill/tag-skill.css
  src/components/tag-skill/tag-skill.jsx
  src/components/tag-skill/tag-skill.md
  src/components/tag-skill/tag-skill.test.jsx
  src/components/tag/__snapshots__/tag.test.jsx.snap
  src/components/tag/tag.css
  src/components/tag/tag.jsx
  src/components/tag/tag.md
  src/components/tag/tag.test.jsx
  src/svgs/icon-clear-small.svg
  src/svgs/icon-tick.svg
  yarn.lock
Labels: component

#123 Add typography-v2 css variables
  CHANGELOG.md
  src/styles/typography-v2.css
Labels: accessibility, misc

#126 Export the list of linted properties for static analysis capabilities
  src/linters/colors.js
  src/linters/colors.test.js
Labels: linter

#127 v0.23.0
  CHANGELOG.md
  package.json
Labels: release

#125 Add linter for Typography
  .stylelintrc.js
  CHANGELOG.md
  src/components/button/button.css
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/icon-all/icon-all.css
  src/components/input/input.css
  src/components/table/table.css
  src/components/tag/tag.css
  src/linters/typography.js
  src/linters/typography.test.js
  styleguide/components/components-list/components-list.css
  styleguide/components/header/header.css
  styleguide/components/link/link.css
  styleguide/components/tab-button/tab-button.css
  styleguide/content/brand-identity/colors.css
  styleguide/content/brand-identity/spacing.css
  styleguide/content/brand-identity/typography.css
  styleguide/content/content.css
  styleguide/content/overview/overview.css
Labels: misc

#122 Multi-choice component
  CHANGELOG.md
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/section-row/section-row.css
  src/components/tag-list/__snapshots__/tag-list.test.jsx.snap
  src/components/tag-list/tag-list.css
  src/components/tag-list/tag-list.jsx
  src/components/tag-list/tag-list.md
  src/components/tag-list/tag-list.test.jsx
  src/components/tag/tag.css
  src/components/tag/tag.jsx
Labels: component

#131 Release 0.24.0
  CHANGELOG.md
  package.json
Labels: release

#130 [webinf-don-t-want-to-your-monkey-list-173316979] Make the listbox component
  CHANGELOG.md
  src/components/list-option/__snapshots__/list-option.test.jsx.snap
  src/components/list-option/list-option.css
  src/components/list-option/list-option.jsx
  src/components/list-option/list-option.md
  src/components/list-option/list-option.test.jsx
  src/components/listbox/__snapshots__/listbox.test.jsx.snap
  src/components/listbox/listbox.css
  src/components/listbox/listbox.jsx
  src/components/listbox/listbox.md
  src/components/listbox/listbox.test.jsx
Labels: component

#134 v0.25.0
  CHANGELOG.md
  package.json
Labels: release

#133 [webinf-if-you-have-typography-in-your-heart-who-am-i-to-judge-you-173299435] Update Typography docs
  styleguide/content/brand-identity/typography.css
  styleguide/content/brand-identity/typography.md
Labels: misc

#129 Implement `FormControl` component
  CHANGELOG.md
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-date/custom-field-input-date.test.jsx
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-number/custom-field-input-number.test.jsx
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/components/form-control/__snapshots__/form-control.test.jsx.snap
  src/components/form-control/form-control.css
  src/components/form-control/form-control.jsx
  src/components/form-control/form-control.md
  src/components/form-control/form-control.test.jsx
  src/components/input/__snapshots__/input.test.jsx.snap
  src/components/input/input.css
  src/components/input/input.jsx
  src/components/input/input.test.jsx
  src/components/list-option/__snapshots__/list-option.test.jsx.snap
  src/components/list-option/list-option.css
  src/components/list-option/list-option.jsx
  src/components/list-option/list-option.md
  src/components/list-option/list-option.test.jsx
  src/components/listbox/__snapshots__/listbox.test.jsx.snap
  src/components/listbox/listbox.css
  src/components/listbox/listbox.jsx
  src/components/listbox/listbox.md
  src/components/listbox/listbox.test.jsx
Labels: component

#135 v0.26.0
  CHANGELOG.md
  package.json
Labels: release

#132 Webinf i can still feel the box 173341864
  src/components/list-option/__snapshots__/list-option.test.jsx.snap
  src/components/list-option/list-option.jsx
  src/components/list-option/list-option.test.jsx
  src/components/listbox/__snapshots__/listbox.test.jsx.snap
  src/components/listbox/listbox.jsx
  src/components/listbox/listbox.md
  src/components/listbox/listbox.test.jsx
  src/components/tag-list/tag-list.md
Labels: component

#137 Forward refs to Button
  CHANGELOG.md
  src/components/button/button.jsx
Labels: component

#136 > [webinf-i-love-all-your-crap-talking-173315047] MDS interactive single choice custom field component (1/4)
  package.json
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.css
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/components/listbox/listbox.jsx
  src/components/listbox/listbox.test.jsx
  yarn.lock
Labels: accessibility, component

#138 Update values to reflect new MDS design tokens
  styleguide.config.js
  styleguide/components/components-list/components-list-container.jsx
  styleguide/components/components-list/components-list.css
  styleguide/components/components-list/components-list.jsx
  styleguide/components/header/header.css
  styleguide/components/header/header.jsx
  styleguide/components/hero/animations.jsx
  styleguide/components/hero/astronauts.css
  styleguide/components/hero/hero.css
  styleguide/components/hero/stars.css
  styleguide/components/hero/stars.jsx
  styleguide/components/link/link.css
  styleguide/components/section/section.css
  styleguide/components/section/section.jsx
  styleguide/components/styleguide/styleguide.css
  styleguide/components/styleguide/styleguide.jsx
  styleguide/components/tab-button/tab-button.css
  styleguide/content/brand-identity/brand-identity.css
  styleguide/content/brand-identity/colors.css
  styleguide/content/brand-identity/spacing.css
  styleguide/content/brand-identity/spacing.md
  styleguide/content/content.css
  styleguide/content/guidelines/legacy.md
  styleguide/content/overview/overview.css
  styleguide/content/overview/overview.md
Labels: site
