Repository mavenlink/design-system, pull requests merged in 2020-04, with the labels that each got.

#87 Release 0.17.0
  CHANGELOG.md
Labels: release

#88 Bump version in package.json for 0-17 release
  package.json
Labels: release

#89 [webinf-oops-forgot-all-the-read-only] Readonly attribute was not included on Number custom field
  CHANGELOG.md
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-number/custom-field-input-number.test.jsx
Labels: component

#90 Release 0.18.0
  CHANGELOG.md
  package.json
Labels: release

#92 Modify the CustomFieldInputCurrency value API to only accept subunits
  CHANGELOG.md
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.md
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
Labels: component

#95 Ensure readonly and disabled currency component does not enter edit mode
  CHANGELOG.md
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
Labels: bug, component
