Repository mavenlink/design-system, pull requests merged in 2020-10, with the labels that each got.

#200 Add maxLength attribute support to text and abstract custom fields
  CHANGELOG.md
  src/components/__internal__/abstract-custom-field/abstract-custom-field.jsx
  src/components/__internal__/abstract-custom-field/abstract-custom-field.test.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-text/custom-field-input-text.jsx
Labels: component

#202 V0.44.1
  CHANGELOG.md
  package.json
  src/components/select/select.md
Labels: release

#203 Release 0.45.0
  CHANGELOG.md
  package.json
Labels: release

#204 Documenting best practices
  .circleci/config.yml
  docs/contributing.md
  docs/documentation.md
  docs/releases.md
  docs/testing.md
  package.json
  yarn.lock
Labels: misc

#205 Deprecate `inputRef` APIs on custom fields
  .circleci/config.yml
  CHANGELOG.md
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-number/custom-field-input-number.test.jsx
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
Labels: component

#206 fix(doc): Form example hooks into single and multi choice changes
  src/components/form/form.md
Labels: misc

#209 Internal MDS inputs look good when required
  CHANGELOG.md
  src/components/form-control/form-control.css
Labels: bug, component

#210 Release 0.46.1
  CHANGELOG.md
  package.json
Labels: release

#201 Webinf date input feedback #174936567
  CHANGELOG.md
  src/components/calendar/calendar.css
  src/components/calendar/calendar.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-date/custom-field-date.css
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-date/custom-field-input-date.md
  src/components/custom-field-input-date/custom-field-input-date.test.jsx
  src/components/custom-field-input-date/format/format-date.js
  src/components/custom-field-input-date/format/format-date.test.js
Labels: bug

#211 Fixes icon form stuff
  .github/pull_request_template.md
  CHANGELOG.md
  docs/documentation.md
  src/components/form/form.md
  src/components/icon-button/icon-button.jsx
  src/components/icon-button/icon-button.md
  src/components/icon-button/icon-button.test.jsx
  src/components/icon/icon.jsx
  src/components/icon/icon.md
  src/components/icon/icon.test.jsx
  src/components/tag-list/__snapshots__/tag-list.test.jsx.snap
  src/components/tag/__snapshots__/tag.test.jsx.snap
  src/components/tag/tag.test.jsx
Labels: accessibility, bug, component, misc

#212 V0.47.0
  CHANGELOG.md
  docs/releases.md
  package.json
Labels: release

#213 Form `autoSave` prop API
  CHANGELOG.md
  package.json
  src/components/form/form.jsx
  src/components/form/form.md
  src/components/form/form.test.jsx
  yarn.lock
Labels: component

#215 Release 0.48.0
  CHANGELOG.md
  package.json
Labels: release

#216 Update release instructions with git push tags
  docs/releases.md
Labels: misc

#220 Fix Select: input state is restored or cleared when closing the dropdown
  .eslintrc.js
  CHANGELOG.md
  src/components/select/select.jsx
  src/components/select/select.test.jsx
  src/hooks/__snapshots__/use-dropdown-close.test.jsx.snap
  src/hooks/use-dropdown-close.js
  src/hooks/use-dropdown-close.test.jsx
Labels: bug, component

#214 Fix issue where validation hook was not re-rendering on changes and w…
  CHANGELOG.md
  src/components/__internal__/abstract-custom-field/abstract-custom-field.css
  src/components/__internal__/abstract-custom-field/abstract-custom-field.jsx
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/components/select/select.jsx
  src/hooks/use-validation.jsx
  src/hooks/use-validation.test.jsx
Labels: bug

#221 Check ref.current before running debounce onSubmit function
  CHANGELOG.md
  src/components/form/form.jsx
Labels: bug

#222 Release 0.48.1
  CHANGELOG.md
  package.json
Labels: release

#217 Fix issue where presentDateString was not considering the user's timezone
  CHANGELOG.md
  src/components/custom-field-input-date/custom-field-input-date.jsx
Labels: bug

#219 Toggle the code snippets to make it easier to QA accessibility
  CHANGELOG.md
  styleguide/components/react-component/react-component.jsx
Labels: misc

#226 Add autoComplete prop for Abstract, use in Select
  CHANGELOG.md
  src/components/__internal__/abstract-custom-field/abstract-custom-field.jsx
  src/components/__internal__/abstract-custom-field/abstract-custom-field.test.jsx
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/select/__snapshots__/select.test.jsx.snap
  src/components/select/select.jsx
  src/components/select/select.test.jsx
Labels: bug

#229 fix(CustomFieldInputMultipleChoice)
  CHANGELOG.md
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
Labels: bug

#227 Bugfix: Select already selected
  CHANGELOG.md
  src/components/listbox/__snapshots__/listbox.test.jsx.snap
  src/components/listbox/listbox.jsx
  src/components/listbox/listbox.test.jsx
  src/components/select/select.test.jsx
Labels: bug

#230 v0.49.0
  CHANGELOG.md
  docs/releases.md
  package.json
Labels: release

#225 MDS Input v3
  CHANGELOG.md
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.md
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.md
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/components/input/__snapshots__/input.test.jsx.snap
  src/components/input/input.css
  src/components/input/input.jsx
  src/components/input/input.md
  src/components/input/input.test.jsx
  src/hooks/use-did-mount.js
Labels: component, misc

#231 v0.50.0
  CHANGELOG.md
  package.json
Labels: release

#232 Webinf taglist nav has no memory of this place 173632521
  CHANGELOG.md
  src/components/tag-list/tag-list.jsx
  src/components/tag-list/tag-list.test.jsx
  src/components/tag/tag.jsx
  src/components/tag/tag.test.jsx
Labels: bug, component

#233 Release 0.51.0
  CHANGELOG.md
  package.json
Labels: release

#235 Webinf honey i fixed the calendar 175313159
  CHANGELOG.md
  src/components/calendar/calendar.css
Labels: bug, component
