Repository mavenlink/design-system, pull requests merged in 2020-08, with the labels that each got.

#160 Webinf you may now so choose one 171681540
  CHANGELOG.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
Labels: component

#168 v0.35.0
  CHANGELOG.md
  package.json
Labels: release

#166 Calendar component
  CHANGELOG.md
  jest.config.transform.svg.js
  src/components/calendar/__snapshots__/calendar.test.jsx.snap
  src/components/calendar/calendar.css
  src/components/calendar/calendar.jsx
  src/components/calendar/calendar.md
  src/components/calendar/calendar.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/icon-button/__snapshots__/icon-button.test.jsx.snap
  src/components/icon-button/icon-button.css
  src/components/icon-button/icon-button.jsx
  src/components/icon-button/icon-button.md
  src/components/icon-button/icon-button.test.jsx
  src/components/icon/__snapshots__/icon.test.jsx.snap
  src/components/icon/icon.jsx
  src/components/icon/icon.test.jsx
  src/components/tag-skill/__snapshots__/tag-skill.test.jsx.snap
  src/svgs/arrow-left.svg
  src/svgs/arrow-right.svg
  src/svgs/caret-down.svg
Labels: component

#164 [webinf-brand-is-motion-identity-is-repetition-173990439] Collapse brand identity in styleguide config
  CHANGELOG.md
  styleguide.config.js
Labels: misc

#172 v0.36.0
  CHANGELOG.md
  package.json
Labels: release

#167 Add aria-haspopup to single and mulit choice inputs for accessibility
  src/components/__internal__/abstract-custom-field/abstract-custom-field.jsx
  src/components/__internal__/abstract-custom-field/abstract-custom-field.test.jsx
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/listbox/listbox.jsx
Labels: accessibility

#175 Ensure markdown paragraphs are styled correctly
  styleguide.config.js
Labels: site

#178 [webinf-loading-loading-loading-loading-loading-174262474] Promoting the loader
  CHANGELOG.md
  docs/component_promotion.md
  src/components/loader/__snapshots__/loader.test.jsx.snap
  src/components/loader/loader.css
  src/components/loader/loader.jsx
  src/components/loader/loader.md
  src/components/loader/loader.test.jsx
Labels: component

#179 Release 0.36.2
  CHANGELOG.md
  package.json
Labels: release

#180 Release 0.37.0
  CHANGELOG.md
  package.json
Labels: release

#170 Webinf why choose just one 171681550
  CHANGELOG.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
Labels: component

#181 Release 0.38.0
  CHANGELOG.md
  package.json
Labels: release

#171 Calendar Component: keyboard navigation
  CHANGELOG.md
  jest.config.globalSetup.js
  jest.config.js
  src/components/calendar/__snapshots__/calendar.test.jsx.snap
  src/components/calendar/calendar.css
  src/components/calendar/calendar.jsx
  src/components/calendar/calendar.md
  src/components/calendar/calendar.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/icon-button/icon-button.jsx
  src/components/icon/__snapshots__/icon.test.jsx.snap
  src/components/icon/icon.jsx
  src/components/tag-list/__snapshots__/tag-list.test.jsx.snap
  src/components/tag-skill/__snapshots__/tag-skill.test.jsx.snap
  src/components/tag/__snapshots__/tag.test.jsx.snap
Labels: accessibility

#176 Calendar Component: year view
  CHANGELOG.md
  src/components/calendar/calendar.css
  src/components/calendar/calendar.jsx
  src/components/calendar/calendar.test.jsx
  src/components/list-option/list-option.jsx
  src/components/list-option/list-option.test.jsx
Labels: component
