Repository mavenlink/design-system, pull requests merged in 2020-09, with the labels that each got.

#177 MDS Linter: spacing variables
  .stylelintrc.js
  CHANGELOG.md
  package.json
  src/linters/spacing.js
  src/linters/spacing.test.js
  styleguide/components/components-list/components-list.css
  styleguide/components/playground/playground.css
  styleguide/components/react-component/react-component.css
  styleguide/components/tab-button/tab-button.css
Labels: linter

#184 Add defaultValue API to Input component
  CHANGELOG.md
  src/components/input/input.jsx
  src/components/input/input.test.jsx
Labels: component

#185 Release 0.40.0
  CHANGELOG.md
  package.json
Labels: release

#187 v0.41.0
  CHANGELOG.md
  package.json
Labels: release

#182 MDS Custom Field Date component uses Calendar component
  CHANGELOG.md
  jest.config.setup.files.after.env.js
  src/components/__internal__/abstract-custom-field/abstract-custom-field.jsx
  src/components/__internal__/abstract-custom-field/abstract-custom-field.test.jsx
  src/components/calendar/calendar.css
  src/components/calendar/calendar.jsx
  src/components/calendar/calendar.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-date/custom-field-date.css
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-date/custom-field-input-date.md
  src/components/custom-field-input-date/custom-field-input-date.test.jsx
  styleguide/components/playground/playground.css
Labels: component

#188 Add className API to Tag, fix input sizing for multi-choice
  CHANGELOG.md
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/tag/tag.css
  src/components/tag/tag.jsx
  src/components/tag/tag.test.jsx
Labels: bug, component

#189 Form control component improvements for generalized MDS Form
  CHANGELOG.md
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-date/custom-field-input-date.test.jsx
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-number/custom-field-input-number.test.jsx
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-text/__snapshots__/custom-field-input-text.test.jsx.snap
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/components/form/__snapshots__/form.test.jsx.snap
  src/components/form/form.css
  src/components/form/form.jsx
  src/components/form/form.md
  src/components/form/form.test.jsx
Labels: component, refactor

#190 v0.42.0 v0.42.1
  CHANGELOG.md
  package.json
  src/components/form/form.md
Labels: release

#192 Add submitText prop to form component
  CHANGELOG.md
  src/components/form/form.jsx
  src/components/form/form.test.jsx
Labels: component

#194 Release 0.43.3
  CHANGELOG.md
  package.json
Labels: release

#193 Select Component and CustomFieldInputSingleChoice Refactor
  CHANGELOG.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/list-option/list-option.css
  src/components/list-option/list-option.jsx
  src/components/list-option/list-option.test.jsx
  src/components/select/__snapshots__/select.test.jsx.snap
  src/components/select/select.css
  src/components/select/select.jsx
  src/components/select/select.md
  src/components/select/select.test.jsx
Labels: component, refactor
