Repository mavenlink/design-system, pull requests merged in 2020-05, with the labels that each got.

#94 [webinf-touissant-l-ouverture-171681683] User sees a (readonly) date field
  CHANGELOG.md
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-text/custom-field-input-text.css
  src/svgs/icon-calendar-fill.svg
Labels: component

#96 v0.19.1
  CHANGELOG.md
  package.json
Labels: release

#97 [webinf-oops-i-broke-the-error-again] Fix documentation issue
  src/components/custom-field-input-currency/custom-field-input-currency.md
Labels: misc

#98 [release-0.19.2] Setup new release
  CHANGELOG.md
Labels: release

#102 Release 0.20.0
  CHANGELOG.md
  package.json
Labels: release

#101 [webinf-i-m-a-token-driver-on-a-long-ride-172248574] Tokenize and documentize color palette in MDS
  CHANGELOG.md
  src/styles/colors-v2.css
  styleguide.config.js
  styleguide/assets/images/message-error.jpg
  styleguide/assets/images/message-success.jpg
  styleguide/assets/images/message-warning.jpg
  styleguide/components/hero/animations.jsx
  styleguide/components/hero/hero.css
  styleguide/components/section/section.jsx
  styleguide/content/brand-identity/brand-identity.css
  styleguide/content/brand-identity/colors.css
  styleguide/content/brand-identity/colors.md
  styleguide/content/brand-identity/typography.css
  styleguide/content/brand-identity/typography.md
  styleguide/content/content.css
  styleguide/content/soul/colors.css
  styleguide/content/soul/colors.md
Labels: misc

#103 release 0.20.1
  CHANGELOG.md
  package.json
Labels: release

#104 Stylelint for missed MDS color usages
  .stylelintrc.js
  CHANGELOG.md
  README.md
  jest.config.js
  package.json
  src/components/button/button.css
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/icon/icon.css
  src/components/input/input.css
  src/components/table/table.css
  src/linters/colors.js
  src/linters/colors.test.js
  src/styles/colors-v2.css
  src/styles/typography.css
  styleguide/components/components-list/components-list.css
  styleguide/components/header/header.css
  styleguide/components/link/link.css
  styleguide/components/playground/playground.css
  styleguide/components/react-component/react-component.css
  styleguide/components/styleguide/styleguide.css
  styleguide/components/table/table.css
  styleguide/content/brand-identity/typography.css
  styleguide/content/overview/overview.css
  yarn.lock
Labels: misc

#105 v0.20.2
  CHANGELOG.md
  package.json
Labels: release

#106 Webinf fix invalid alpha values
  CHANGELOG.md
  src/styles/colors-v2.css
  styleguide/components/components-list/components-list.css
  styleguide/components/header/header.css
Labels: bug

#107 Release 0.20.3
  CHANGELOG.md
Labels: release

#108 PageHeader component
  CHANGELOG.md
  src/components/page-header/__snapshots__/page-header.test.jsx.snap
  src/components/page-header/page-header.css
  src/components/page-header/page-header.jsx
  src/components/page-header/page-header.md
  src/components/page-header/page-header.test.jsx
Labels: component

#110 Webinf row row row your section 172923835
  CHANGELOG.md
  src/components/section-row/__snapshots__/section-row.test.jsx.snap
  src/components/section-row/section-row.css
  src/components/section-row/section-row.jsx
  src/components/section-row/section-row.md
  src/components/section-row/section-row.test.jsx
  src/components/section/section.md
Labels: component

#109 Implement Section component
  CHANGELOG.md
  src/components/section-row/__snapshots__/section-row.test.jsx.snap
  src/components/section-row/section-row.css
  src/components/section-row/section-row.jsx
  src/components/section-row/section-row.md
  src/components/section-row/section-row.test.jsx
  src/components/section/__snapshots__/section.test.jsx.snap
  src/components/section/section.css
  src/components/section/section.jsx
  src/components/section/section.md
  src/components/section/section.test.jsx
Labels: component

#112 Fix centering issue
  CHANGELOG.md
  src/components/custom-field-input-text/custom-field-input-text.css
Labels: bug

#113 Release 0.21.0
  CHANGELOG.md
  package.json
Labels: release

#114 Ensure styleguide files are published
  CHANGELOG.md
  package.json
Labels: misc

#115 v0.22.0
  CHANGELOG.md
  package.json
Labels: release

#111 [webinf-dee-aa-doo-doo-dee-aa-doo-doo172781965] Page Patterns Page
  CHANGELOG.md
  styleguide.config.js
  styleguide/assets/images/page-margins-example.jpg
  styleguide/assets/images/page-title-margins.jpg
  styleguide/assets/images/page-title-no-text.jpg
  styleguide/assets/images/section-buttons-space-between.jpg
  styleguide/assets/images/section-header-margins-2.jpg
  styleguide/assets/images/section-header-margins-no-description.jpg
  styleguide/assets/images/section-header-margins-with-components.jpg
  styleguide/assets/images/section-header-margins.jpg
  styleguide/assets/images/section-margins-with-buttons.jpg
  styleguide/assets/images/section-margins-without-buttons.jpg
  styleguide/assets/images/section-space-between.jpg
  styleguide/content/brand-identity/brand-identity.css
  styleguide/content/brand-identity/spacing.css
  styleguide/content/brand-identity/spacing.md
  styleguide/content/design-patterns/basic-page-spacing.md
Labels: misc
