Repository mavenlink/design-system, pull requests merged in 2021-05, with the labels that each got.

#296 MDS Percentage component
  CHANGELOG.md
  src/components/form-control-icons/__snapshots__/form-control-icons.test.jsx.snap
  src/components/form-control-icons/form-control-icons.css
  src/components/form-control-icons/form-control-icons.jsx
  src/components/form-control-icons/form-control-icons.md
  src/components/form-control-icons/form-control-icons.test.jsx
  src/components/percentage/__snapshots__/percentage.test.jsx.snap
  src/components/percentage/percentage.css
  src/components/percentage/percentage.jsx
  src/components/percentage/percentage.md
  src/components/percentage/percentage.test.jsx
Labels: component

#302 Release 0.68.0
  CHANGELOG.md
  package.json
Labels: release

#300 Create checkbox
  CHANGELOG.md
  src/components/checkbox/__snapshots__/checkbox.test.jsx.snap
  src/components/checkbox/checkbox.css
  src/components/checkbox/checkbox.jsx
  src/components/checkbox/checkbox.md
  src/components/checkbox/checkbox.test.jsx
Labels: component

#304 feat(Form): add `className` API
  CHANGELOG.md
  src/components/form/form.jsx
  src/components/form/form.test.jsx
Labels: component

#305 v0.70.0
  CHANGELOG.md
  package.json
Labels: release

#309 MDS Popover#shouldClose API, MDS Checkbox#readOnly fix
  CHANGELOG.md
  jest.config.setup.files.after.env.js
  package.json
  src/components/checkbox/checkbox.css
  src/components/checkbox/checkbox.jsx
  src/components/checkbox/checkbox.md
  src/components/checkbox/checkbox.test.jsx
  src/components/custom-field-input-multiple-choice/test-queries.js
  src/components/custom-field-input-single-choice/test-queries.js
  src/components/date/date.test.jsx
  src/components/popover/__snapshots__/popover.test.jsx.snap
  src/components/popover/popover.jsx
  src/components/popover/popover.md
  src/components/popover/popover.test.jsx
  src/components/ref-example/ref-example.jsx
  yarn.lock
Labels: component

#312 fix(test-queries): ensure `waitForElementToBeRemoved` is given a valid element
  CHANGELOG.md
  src/components/custom-field-input-multiple-choice/test-queries.js
  src/components/custom-field-input-single-choice/test-queries.js
Labels: refactor

#314 v0.72.1
  CHANGELOG.md
  package.json
Labels: release

#316 Upgrade styleguidist
  package.json
  styleguide.config.js
  styleguide.styles.config.js
  styleguide/components/hero/animations.jsx
  styleguide/components/hero/astro-1.svg
  styleguide/components/hero/astro-2.svg
  styleguide/components/hero/astro-with-browser2.svg
  styleguide/components/hero/astronauts.css
  styleguide/components/hero/astros-browser.svg
  styleguide/components/hero/astros-laptop.svg
  styleguide/components/hero/goth-dancer.svg
  styleguide/components/hero/hero.css
  styleguide/components/hero/hero.jsx
  styleguide/components/hero/maven-constellation.svg
  styleguide/components/hero/mds-components.jpeg
  styleguide/components/hero/mds-guidelines.jpeg
  styleguide/components/hero/mds-hero.jpeg
  styleguide/components/hero/mds-soul.jpeg
  styleguide/components/hero/singer-dancers.svg
  styleguide/components/hero/singer-flying.svg
  styleguide/components/hero/singers.svg
  styleguide/components/hero/star-lg.svg
  styleguide/components/hero/stars.css
  styleguide/components/hero/stars.jsx
  styleguide/components/playground/index.js
  styleguide/components/playground/playground.css
  styleguide/components/playground/playground.jsx
  styleguide/components/react-component/index.js
  styleguide/components/react-component/react-component.css
  styleguide/components/react-component/react-component.jsx
  styleguide/components/section/section.jsx
  styleguide/components/styleguide/styleguide.css
  styleguide/components/tab-button/index.js
  styleguide/components/tab-button/tab-button.css
  styleguide/components/tab-button/tab-button.jsx
  yarn.lock
Labels: dependencies, site

#317 Input / Number: run validations onBlur only, not blur + change
  CHANGELOG.md
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/components/input/input.jsx
  src/components/input/input.test.jsx
  src/components/number/number.jsx
  src/components/number/number.test.jsx
Labels: bug

#318 v0.72.2
  CHANGELOG.md
  package.json
Labels: release

#311 MDS Multi-Select
  CHANGELOG.md
  src/components/multi-select/__snapshots__/multi-select.test.jsx.snap
  src/components/multi-select/multi-select.css
  src/components/multi-select/multi-select.jsx
  src/components/multi-select/multi-select.md
  src/components/multi-select/multi-select.test.jsx
  src/components/multi-select/test-queries.js
Labels: component
