Repository mavenlink/design-system, pull requests merged in 2021-04, with the labels that each got.

#285 feat(CustomFieldInputMultipleChoice): add self-loading of choices
  CHANGELOG.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-multiple-choice/test-queries.js
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/mock-handlers.js
  yarn.lock
Labels: component

#289 v0.63.0
  CHANGELOG.md
  package.json
Labels: release

#287 fix(custom-field-input-date): does not offset value when a date with …
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-date/custom-field-input-date.test.jsx
Labels: bug

#290 v0.63.1
  CHANGELOG.md
  package.json
Labels: release

#288 MDS Page Patterns v2
  .eslintrc.js
  pages/design-patterns/basic-page-spacing.md
  pages/design-patterns/images/page-margins-example.jpg
  pages/design-patterns/images/page-title-margins.jpg
  pages/design-patterns/images/page-title-no-text.jpg
  pages/design-patterns/images/section-buttons-space-between.jpg
  pages/design-patterns/images/section-header-margins-2.jpg
  pages/design-patterns/images/section-header-margins-no-description.jpg
  pages/design-patterns/images/section-header-margins-with-components.jpg
  pages/design-patterns/images/section-header-margins.jpg
  pages/design-patterns/images/section-margins-with-buttons.jpg
  pages/design-patterns/images/section-margins-without-buttons.jpg
  pages/design-patterns/images/section-space-between.jpg
  pages/design-patterns/pages/form-type.md
  pages/design-patterns/pages/hybrid-type.md
  pages/design-patterns/pages/images/image1.jpg
  pages/design-patterns/pages/images/image10.jpg
  pages/design-patterns/pages/images/image11.jpg
  pages/design-patterns/pages/images/image2.jpg
  pages/design-patterns/pages/images/image3.jpg
  pages/design-patterns/pages/images/image4.jpg
  pages/design-patterns/pages/images/image5.jpg
  pages/design-patterns/pages/images/image6.jpg
  pages/design-patterns/pages/images/image7.jpg
  pages/design-patterns/pages/images/image8.jpg
  pages/design-patterns/pages/images/image9.jpg
  pages/design-patterns/pages/index.md
  pages/design-patterns/pages/project-view-type.md
  pages/design-patterns/pages/table-type.md
  pages/index.css
  styleguide.config.js
  styleguide.config.styles.js
  styleguide.styles.config.js
  styleguide/.eslintrc
  styleguide/components/components-list/components-list-container.jsx
  styleguide/content/content.css
  styleguide/webpack.config.js
Labels: site

#282 Fix first render to not show errors for select.jsx when its required
  CHANGELOG.md
  src/components/listbox/__snapshots__/listbox.test.jsx.snap
  src/components/listbox/listbox.jsx
  src/components/select/select.jsx
  src/components/select/select.md
  src/components/select/select.test.jsx
Labels: bug

#291 Webinf textarea 176747702
  CHANGELOG.md
  src/components/textarea/__snapshots__/textarea.test.jsx.snap
  src/components/textarea/mock-handlers.js
  src/components/textarea/textarea.css
  src/components/textarea/textarea.jsx
  src/components/textarea/textarea.md
  src/components/textarea/textarea.test.jsx
  styleguide/utils/include-msw.js
Labels: component

#295 Release 0.65.0
  CHANGELOG.md
Labels: release

#293 MDS Date component
  .eslintrc.js
  CHANGELOG.md
  jest.config.setup.files.after.env.js
  src/components/calendar/__snapshots__/calendar.test.jsx.snap
  src/components/calendar/calendar.jsx
  src/components/calendar/calendar.md
  src/components/calendar/calendar.test.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-date/custom-field-input-date.md
  src/components/custom-field-input-date/custom-field-input-date.test.jsx
  src/components/date/__snapshots__/date.test.jsx.snap
  src/components/date/date.css
  src/components/date/date.jsx
  src/components/date/date.md
  src/components/date/date.test.jsx
  src/components/form-control/form-control.css
  src/components/ref-example/ref-example.jsx
  src/components/select/select.test.jsx
  yarn.lock
Labels: component

#297 v0.66.0
  CHANGELOG.md
  package.json
Labels: release
