Repository mavenlink/design-system, pull requests merged in 2021-02, with the labels that each got.

#266 Fix styling bug
  CHANGELOG.md
  src/components/custom-field-input-date/custom-field-date.css
Labels: bug

#267 v0.56.1
  CHANGELOG.md
  package.json
Labels: release

#268 Page header remove margin
  CHANGELOG.md
  package.json
  src/components/form/form.test.jsx
  src/components/page-header/__snapshots__/page-header.test.jsx.snap
  src/components/page-header/page-header.css
  src/components/page-header/page-header.jsx
  src/components/page-header/page-header.test.jsx
Labels: component, release

#270 Implement updatable value APIs on Select and SingleChoice components
  .eslintrc.js
  .gitignore
  CHANGELOG.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/input/input.jsx
  src/components/input/input.test.jsx
  src/components/number/number.jsx
  src/components/select/select.jsx
  src/components/select/select.test.jsx
  src/hooks/use-did-mount.js
  src/hooks/use-mounted.js
  src/hooks/use-validation.jsx
Labels: component

#272 v0.58.0
  .circleci/config.yml
  CHANGELOG.md
  package.json
Labels: release

#273 MDS CustomFieldInputNumber: value API is an <integer>
  CHANGELOG.md
  package.json
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-number/custom-field-input-number.test.jsx
  src/components/number/number.test.jsx
Labels: bug

#276 MDS multi-choice improvements: placeholder, required, className
  CHANGELOG.md
  docs/documentation.md
  package.json
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-multiple-choice/test-queries.js
  src/components/no-options/no-options.jsx
Labels: accessibility, component
