Repository mavenlink/design-system, pull requests merged in 2021-03, with the labels that each got.

#269 MDS CustomFieldSingleChoice fetches its own choices
  .eslintrc.js
  CHANGELOG.md
  jest.config.js
  jest.config.setup.files.after.env.js
  package.json
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-single-choice/mock-handlers.js
  src/components/custom-field-input-single-choice/test-queries.js
  src/components/list-option/list-option.jsx
  src/components/list-option/list-option.md
  src/components/list-option/mock-handlers.js
  src/mocks/jest-server.js
  src/mocks/jest-server.test.js
  src/mocks/mock-constants.js
  styleguide.config.js
  styleguide/utils/include-msw.js
  yarn.lock
Labels: component, dependencies, misc, site

#279 V0.61.0
  CHANGELOG.md
  package.json
Labels: release

#280 Webinf single choice loading 176989566
  CHANGELOG.md
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-single-choice/mock-handlers.js
  src/components/custom-field-input-single-choice/test-queries.js
  styleguide/utils/include-msw.js
Labels: component, misc, site

#281 V0.62.0
  CHANGELOG.md
  package.json
Labels: release

#283 fix(inputs): ensure inputs use MDS fonts with a height of 32px
  CHANGELOG.md
  src/components/__internal__/abstract-custom-field/abstract-custom-field.css
  src/components/input/input.css
Labels: bug

#284 v0.62.1
  CHANGELOG.md
  package.json
Labels: release
