Repository mavenlink/design-system, pull requests merged in 2021-01, with the labels that each got.

#258 Adjust styling of form
  CHANGELOG.md
  src/components/form/form.css
Labels: bug

#259 Release 0.53.3
  CHANGELOG.md
  package.json
Labels: release

#260 Currency component can update its value given new `value`
  CHANGELOG.md
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-currency/custom-field-input-currency.test.jsx
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-number/custom-field-input-number.test.jsx
  src/components/custom-field-input-text/custom-field-input-text.jsx
  src/components/custom-field-input-text/custom-field-input-text.test.jsx
  src/components/number/number.jsx
Labels: bug, component

#262 v0.54.0
  CHANGELOG.md
  package.json
Labels: release

#261 Webinf configure form submit button alignment 176466149
  CHANGELOG.md
  src/components/form/form.jsx
  src/components/form/form.test.jsx
Labels: component, misc

#263 Release v0.55.0
  CHANGELOG.md
Labels: release

#264 CustomFieldInputDate updates: `value` and `readOnly`
  CHANGELOG.md
  src/components/custom-field-input-date/custom-field-input-date.jsx
  src/components/custom-field-input-date/custom-field-input-date.test.jsx
Labels: component

#265 v0.56.0
  CHANGELOG.md
  package.json
Labels: release
