Repository mavenlink/design-system, pull requests merged in 2021-08, with the labels that each got.

#354 MDS Select Dropdown Max Height
  CHANGELOG.md
  src/components/select/select.css
  src/components/select/select.md
Labels: component

#355 Release 0.80.1
  CHANGELOG.md
Labels: release

#353 Select cell
  .eslintrc.js
  CHANGELOG.md
  jest.config.globalSetup.js
  package.json
  src/components/__internal__/abstract-custom-field/abstract-custom-field.css
  src/components/__internal__/abstract-custom-field/abstract-custom-field.jsx
  src/components/__internal__/abstract-custom-field/abstract-custom-field.test.jsx
  src/components/autocompleter/__snapshots__/autocompleter.test.jsx.snap
  src/components/cell-control/cell-control.jsx
  src/components/cell-control/input.md
  src/components/cell-control/select.jsx
  src/components/cell-control/select.md
  src/components/control/select.jsx
  src/components/custom-field-input-currency/__snapshots__/custom-field-input-currency.test.jsx.snap
  src/components/custom-field-input-currency/custom-field-input-currency.jsx
  src/components/custom-field-input-date/custom-field-date.css
  src/components/custom-field-input-number/__snapshots__/custom-field-input-number.test.jsx.snap
  src/components/custom-field-input-number/custom-field-input-number.jsx
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-text/custom-field-input-text.css
  src/components/form-control/form-control.jsx
  src/components/select/__snapshots__/select.test.jsx.snap
  src/components/select/select.css
  src/components/select/select.jsx
  styleguide.config.js
  yarn.lock
Labels: component, refactor

#368 MDS interactive table improvements
  .circleci/config.yml
  CHANGELOG.md
  jest.config.js
  package.json
  src/components/calendar/__snapshots__/calendar.test.jsx.snap
  src/components/cell-control/__snapshots__/autocompleter.test.jsx.snap
  src/components/cell-control/__snapshots__/input.test.jsx.snap
  src/components/cell-control/__snapshots__/select.test.jsx.snap
  src/components/cell-control/autocompleter.jsx
  src/components/cell-control/autocompleter.test.jsx
  src/components/cell-control/cell-control.jsx
  src/components/cell-control/input.jsx
  src/components/cell-control/input.test.jsx
  src/components/cell-control/select.jsx
  src/components/cell-control/select.test.jsx
  src/components/control/input.jsx
  src/components/control/select.jsx
  src/components/custom-field-input-date/__snapshots__/custom-field-input-date.test.jsx.snap
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/date/__snapshots__/date.test.jsx.snap
  src/components/form-control/form-control.css
  src/components/icon-button/__snapshots__/icon-button.test.jsx.snap
  src/components/icon-button/icon-button.jsx
  src/components/icon-button/icon-button.test.jsx
  src/components/multi-autocompleter/__snapshots__/multi-autocompleter.test.jsx.snap
  src/components/multi-select/__snapshots__/multi-select.test.jsx.snap
  src/components/tag-list/__snapshots__/tag-list.test.jsx.snap
  src/components/tag/__snapshots__/tag.test.jsx.snap
  yarn.lock
Labels: component
