Repository mavenlink/design-system, pull requests merged in 2021-09, with the labels that each got.

#375 Select Consumes keydown Event When Dropdown Open
  CHANGELOG.md
  src/components/control/select.jsx
Labels: component, accessibility, WIP

#377 Single choice as an autocompleter
  CHANGELOG.md
  src/components/autocompleter/autocompleter.md
  src/components/autocompleter/mock-handlers.js
  src/components/control/autocompleter.jsx
  src/components/control/select.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-single-choice/__snapshots__/custom-field-input-single-choice.test.jsx.snap
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.test.jsx
  src/components/custom-field-input-single-choice/mock-handlers.js
  src/components/custom-field-input-single-choice/test-queries.js
  src/components/list-option/mock-handlers.js
  src/components/multi-autocompleter/multi-autocompleter.jsx
  src/components/multi-autocompleter/multi-autocompleter.test.jsx
  src/components/select/select.css
  src/components/select/select.md
  src/components/textarea/mock-handlers.js
  src/mocks/jest-server.test.js
  src/mocks/mock-constants.js
  styleguide/utils/include-msw.js
Labels: bug, component

#376 Release 0.85.0
  CHANGELOG.md
  package.json
  src/components/select/select.test.jsx
Labels: release
