Repository mavenlink/design-system, pull requests merged in 2021-07, with the labels that each got.

#336 v0.76.0
  CHANGELOG.md
  package.json
Labels: release

#338 chore(config): pull before push
  .circleci/config.yml
Labels: misc

#333 fix(tooltip): resolve `overflow: hidden` issue
  .eslintrc.js
  CHANGELOG.md
  jest.config.setup.files.after.env.js
  src/components/form-control/form-control.test.jsx
  src/components/help-icon/__snapshots__/help-icon.test.jsx.snap
  src/components/help-icon/help-icon.test.jsx
  src/components/icon/icon.jsx
  src/components/icon/icon.test.jsx
  src/components/input/input.md
  src/components/tooltip/__snapshots__/tooltip.test.jsx.snap
  src/components/tooltip/tooltip.css
  src/components/tooltip/tooltip.jsx
  src/components/tooltip/tooltip.md
  src/components/tooltip/tooltip.test.jsx
  src/components/tooltip/use-tooltip-positioning.js
  src/components/tooltip/use-tooltip-positioning.test.js
Labels: accessibility, bug, component

#340 v0.78.1
  CHANGELOG.md
  package.json
Labels: release

#342 `HelpIcon`: remove bad example from docs
  CHANGELOG.md
  src/components/help-icon/help-icon.md
Labels: component

#343 prevent tooltip "jump" w/ scrollbar + add classNames to help-icon
  CHANGELOG.md
  src/components/help-icon/__snapshots__/help-icon.test.jsx.snap
  src/components/help-icon/help-icon.jsx
  src/components/help-icon/help-icon.test.jsx
  src/components/tooltip/tooltip.css
Labels: component

#347 fix(tooltip): add z index for tooltip so it sits on top
  CHANGELOG.md
  src/components/tooltip/tooltip.css
Labels: bug, component

#345 Refactor CustomFieldInputMultipleChoice
  CHANGELOG.md
  src/components/autocompleter/autocompleter.jsx
  src/components/autocompleter/mock-handlers.js
  src/components/custom-field-input-multiple-choice/__snapshots__/custom-field-input-multiple-choice.test.jsx.snap
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.css
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.jsx
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.md
  src/components/custom-field-input-multiple-choice/custom-field-input-multiple-choice.test.jsx
  src/components/custom-field-input-multiple-choice/test-queries.js
  src/components/custom-field-input-single-choice/mock-handlers.js
  src/components/multi-autocompleter/multi-autocompleter.jsx
  src/components/multi-autocompleter/multi-autocompleter.test.jsx
Labels: component, refactor

#349 Release 0.79.2
  CHANGELOG.md
  package.json
Labels: release

#346 MDS Select fires `onChange` after clearing value
  CHANGELOG.md
  src/components/custom-field-input-single-choice/custom-field-input-single-choice.jsx
  src/components/select/select.jsx
  src/components/select/select.md
  src/components/select/select.test.jsx
Labels: bug, component

#350 Release 0.79.3
  CHANGELOG.md
  package.json
Labels: release

#351 0.80.0
  CHANGELOG.md
  package.json
Labels: release
