Repository mavenlink/design-system, pull requests merged in 2022-05, with the labels that each got.

#450 fix(Money): ensure server validation messages appear after submitting a form
  CHANGELOG.md
  package.json
  src/components/control/money.jsx
  src/components/money-input/money-input.test.jsx
Labels: bug

#453 No leaks in MSW
  .circleci/config.yml
  package.json
  yarn.lock
Labels: dependencies

#451 fix(autocompleter): refetch data on api endpoint url changes
  .circleci/config.yml
  CHANGELOG.md
  package.json
  src/components/autocompleter/autocompleter.test.jsx
  src/components/control/autocompleter.jsx
  yarn.lock
Labels: component

#452 Enhance Date Cell controls
  CHANGELOG.md
  package.json
  src/components/control/date.jsx
  src/components/control/date.test.jsx
  src/components/date/date.test.jsx
  src/components/icon-button/icon-button.jsx
  src/components/icon-button/icon-button.test.jsx
Labels: accessibility

#454 Fix onChange events
  CHANGELOG.md
  src/components/cell-control/__snapshots__/number.test.jsx.snap
  src/components/control/date.jsx
  src/components/control/number.jsx
  src/components/date/date.test.jsx
  src/components/number/__snapshots__/number.test.jsx.snap
  src/components/number/number.test.jsx
Labels: bug

#456 [Api] Add onFocus and onBlur to control cell inputs
  CHANGELOG.md
  src/components/cell-control/autocompleter.jsx
  src/components/cell-control/date.jsx
  src/components/cell-control/input.jsx
  src/components/cell-control/input.test.jsx
  src/components/cell-control/money.jsx
  src/components/cell-control/multi-autocompleter.jsx
  src/components/cell-control/multi-select.jsx
  src/components/cell-control/number.jsx
  src/components/cell-control/number.test.jsx
  src/components/cell-control/select.jsx
  src/components/cell-control/textarea.jsx
  src/components/cell-control/textarea.test.jsx
  src/components/control/autocompleter.jsx
  src/components/control/date.jsx
  src/components/control/date.test.jsx
  src/components/control/money.jsx
  src/components/control/multi-autocompleter.jsx
  src/components/control/multi-select.jsx
  src/components/control/number.jsx
  src/components/control/select.jsx
  src/components/control/select.test.jsx
  src/components/multi-autocompleter/multi-autocompleter.jsx
  src/components/multi-autocompleter/multi-autocompleter.test.jsx
  src/components/multi-select/multi-select.jsx
  src/components/multi-select/multi-select.test.jsx
Labels: misc

#459 [API] expose the `min/max` to number controls
  src/components/cell-control/number.jsx
  src/components/control/number.jsx
  src/components/number/number.jsx
  src/components/number/number.test.jsx
Labels: misc

#461 Add mds-brand-8 color to stylesheet
  package.json
  src/styles/colors-v2.css
Labels: reviewable

#460 feat(Colors): Add low opacity brand color variables, add nav blue bra…
  package.json
  src/styles/colors-v2.css
Labels: misc

#462 Remove legacy Mavenlink colors
  package.json
  src/styles/colors-v2.css
Labels: misc
